<?php

namespace App\Filament\Resources\Documents\Schemas;

use App\Models\Document;
use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class DocumentInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('document_type_id')
                    ->numeric(),
                TextEntry::make('document_number')
                    ->placeholder('-'),
                TextEntry::make('order_number')
                    ->placeholder('-'),
                TextEntry::make('tracking_number')
                    ->placeholder('-'),
                TextEntry::make('items_search')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('status_deprecated')
                    ->placeholder('-'),
                TextEntry::make('documentStatus.name')
                    ->label('Document status'),
                TextEntry::make('issued_at')
                    ->dateTime(),
                TextEntry::make('due_at')
                    ->dateTime(),
                TextEntry::make('grand_subtotal')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('discount_type')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('discount_value')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('tax.name')
                    ->label('Tax')
                    ->placeholder('-'),
                TextEntry::make('tax_value')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('grand_amount')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('currency_code')
                    ->placeholder('-'),
                TextEntry::make('currency_rate')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('document_category_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('customer.name')
                    ->label('Customer')
                    ->placeholder('-'),
                TextEntry::make('customer_name')
                    ->placeholder('-'),
                TextEntry::make('customer_nick')
                    ->placeholder('-'),
                TextEntry::make('customer_email')
                    ->placeholder('-'),
                TextEntry::make('customer_tax_number')
                    ->placeholder('-'),
                TextEntry::make('customer_phone')
                    ->placeholder('-'),
                TextEntry::make('customer_address')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('customer_city')
                    ->placeholder('-'),
                TextEntry::make('customer_zip_code')
                    ->placeholder('-'),
                TextEntry::make('customer_state')
                    ->placeholder('-'),
                TextEntry::make('customer_country')
                    ->placeholder('-'),
                TextEntry::make('notes')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('payment_info')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('attachments_spaces_s3')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('attachments_qc_spaces_s3')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('attachments_packing_spaces_s3')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('attachments_clerk_spaces_s3')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('attachments_delivery_spaces_s3')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('attachments_orderchecker_spaces_s3')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('attachments')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('attachments_qc')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('attachments_packing')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('attachments_clerk')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('documentShipmentType.name')
                    ->label('Document shipment type')
                    ->placeholder('-'),
                TextEntry::make('notes_clerk')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('ship_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('attachments_delivery')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('notes_delivery')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('attachments_orderchecker')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('notes_orderchecker')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('created_by')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('created_name')
                    ->placeholder('-'),
                TextEntry::make('updated_by')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('updated_name')
                    ->placeholder('-'),
                TextEntry::make('panel_name')
                    ->placeholder('-'),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('deleted_at')
                    ->dateTime()
                    ->visible(fn (Document $record): bool => $record->trashed()),
                TextEntry::make('return_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('refunded_at')
                    ->dateTime()
                    ->placeholder('-'),
                IconEntry::make('is_cod')
                    ->boolean(),
                TextEntry::make('paymentSort.name')
                    ->label('Payment sort')
                    ->placeholder('-'),
                TextEntry::make('locked_by')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('locked_at')
                    ->dateTime()
                    ->placeholder('-'),
            ]);
    }
}
